name: Build PDF
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: xu-cheng/texlive-action/full@v1
      - run: pip install git+https://github.com/OCIoficial/ocimatic
      - run: latexmk -pdf parapente/statement/statement.tex
      - run: mkdir pdf
      - run: mv statement.pdf pdf/statement.pdf
      - name: Deploy to branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: pdf
          FOLDER: pdf
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
